### PR TITLE
feat(frontend): improve validation status and filtering

### PR DESCRIPTION
**Pull request by ericboucher**
Fixes a few linked issues by:

- Adding validation status to common fields
- Removing rejected form from home page
- Sorting reports by disaster date, then submission time
- Adding report status indicator on home page
- Getting "All incidents" (excluding Flood and Drought) - will require an APII restart
- Display "No forms found" instead of an empty table

Screenshot 2023-05-17 at 7 03 12 PM

Screenshot 2023-05-17 at 8 22 41 PM

### CODE REVIEW

**Comment by ericboucher** [comment]
@wadhwamatic for "all incidents", is it correct to use key `99` or should we keep `99` to mean "other incidents" and invent a new fake key for "all incidents"?

**Comment by wadhwamatic** [comment]
@ericboucher - thanks for this. A couple of comments:
1. Can we modify the text in the 'Review and Approval' column to list the actual status? Right now, the icon gives an indication of the status, but the text could also read 'Approved', or 'Not Yet Approved'
2. If no forms are found, the search screen is blank. Can we add text that says 'No forms found'

**Comment by wadhwamatic** [comment]
> @wadhwamatic for "all incidents", is it correct to use key `99` or should we keep `99` to mean "other incidents" and invent a new fake key for "all incidents"?

@ericboucher - we should create a new 'fake' key for all incidents

**Comment by ericboucher** [comment]
@wadhwamatic all done, let me know what you think:
Screenshot 2023-05-18 at 4 02 02 PM
Screenshot 2023-05-18 at 4 11 30 PM

**Comment by ericboucher** [comment]
@sifelix this PR is breaking form edits atm. I ge the following error from the API:
`"property _validation_status should not exist"` any idea on how to fix this easily?

**Comment by wadhwamatic** [comment]
Looks good @ericboucher. The only thing that didn't work as expected was selecting 'all incidents' didn't return results even though I get results for storms. 

Storms:
Screenshot 2023-05-18 at 13 29 31

All incidents for the same period:
Screenshot 2023-05-18 at 13 30 52

**Comment by ericboucher** [comment]
@wadhwamatic the "all incidents" won't work until we deploy the backend but it should work once we merge to master. It's working well locally.

**Comment by wadhwamatic** [comment]
> @wadhwamatic the "all incidents" won't work until we deploy the backend but it should work once we merge to master. It's working well locally.

@ericboucher - Ok. We can merge when you're ready and I can verify after

**Pull request merged**
