### PR TITLE
Add charts

### PR DESCRIPTION
**Pull request by ericboucher**
Screenshot 2024-08-14 at 11 03 52 PM

### CODE REVIEW

**Comment by wadhwamatic** [comment]
Looks good, thanks @ericboucher! One small request - can we change the label of the 'charts' button to 'update'?

**Review by wadhwamatic — APPROVED** [review]
GTG, thanks @ericboucher

**Comment by ericboucher** [comment]
@wadhwamatic should we order the locations alphabetically or by number of events?

**Comment by wadhwamatic** [comment]
@ericboucher - I think sorting alphabetically is preferred so users can consistently see regions in the same order. The visualization shows number of events / people affected anyway.

For people affected, I think the simple approach is ok for now, but we should utilize the flood number when time allows. 

The logic on flood number is in the Google doc we worked on. Is there something else we need an answer on from Roth?

**Comment by ericboucher** [comment]
@wadhwamatic I added the floodN logic, see this function here https://github.com/WFP-VAM/dmp/pull/164/files#diff-6f55a849f45d58cce5386d6876e14cf1a97eae7094daa7fff9fbdeb01779a397R28 and also used it for reports.

I sorted alphabetically, the caveat is that the order changes when switching from Khmer to English

**Comment by wadhwamatic** [comment]
Looks good, thanks @ericboucher! For sorting, I assume we have also implemented alphabetic sorting in Khmer?

**Pull request merged**
