### PR TITLE
Download raw data as CSV or Excel

### PR DESCRIPTION
**Pull request by ericboucher**
Add an option to download raw data as CSV per table

Screenshot 2024-09-13 at 7 46 41 PM

### CODE REVIEW

**Comment by wadhwamatic** [comment]
Tested using a flood report for all provinces. I'm only able to see CSV as an option. 
Screenshot 2024-09-13 at 14 33 05

For the downloaded CSV file, should we use location names instead of IDs? And variable labels instead of names?
Screenshot 2024-09-13 at 14 33 37

When I downloaded a CSV from the interface in Khmer, the location data is all concatenated in one column
Screenshot 2024-09-13 at 14 33 45

**Comment by ericboucher** [comment]
Yup the latest version should address that but it's failing to deploy. I'll have a look tomorrow

**Comment by wadhwamatic** [comment]
Thanks @ericboucher. Location issue and access to Excel downloads are both good now. I'm not sure if it's because we haven't added a translation yet or if there's an error, but the download links are not in Khmer.
Screenshot 2024-09-14 at 09 54 45

**Comment by ericboucher** [comment]
Nice catch, we had not added translation in the km file yet. This is resolved:

Screenshot 2024-09-15 at 11 39 00 AM

**Review by wadhwamatic — APPROVED** [review]
gtg, thanks Eric

**Pull request merged**
