### PR TITLE
feat(frontend): reset approval after edit

### PR DESCRIPTION
**Pull request by ericboucher**
Reset approval to onHold after edit

### CODE REVIEW

**Comment by wadhwamatic** [comment]
@ericboucher - The form status changed as expected after I edited. Thanks!

FYI - I just noticed that forms are not showing in reverse chronological order within a date. The last form I submitted is 'AW - test edit flow' but it shows after forms submitted earlier today.

Screenshot 2023-05-18 at 14 42 28

**Comment by ericboucher** [comment]
@wadhwamatic it's ordered by disaster date, would you like the ordering to be something else? Disaster date + edit date?

**Comment by wadhwamatic** [comment]
> @wadhwamatic it's ordered by disaster date, would you like the ordering to be something else? Disaster date + edit date?

@ericboucher - yes, let's do that. First by disaster date, and secondary sort by edit date

**Comment by ericboucher** [comment]
> > @wadhwamatic it's ordered by disaster date, would you like the ordering to be something else? Disaster date + edit date?
> 
> @ericboucher - yes, let's do that. First by disaster date, and secondary sort by edit date

Done in the other PR (it should propagate to this one too)

**Comment by wadhwamatic** [comment]
Looks good now, thanks @ericboucher

**Review by wadhwamatic — APPROVED** [review]
Thanks @ericboucher - this works as expected across the different forms

**Pull request merged**
